version: '3.6'

services:

  web:
    build: web/
    command: python -u app.py
    ports:
      - 5000:5000
    links:
      - db
      - nlp
    environment:
      DB_PORT_27017_TCP_ADDR: db


  db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db

  nlp:
    build: predict/
    command: python lambda_function.py

  plotter:
    image: are-you-fake-news/plotter:0.1.1
    build: 
      context: ./plotter
      target: app
    volumes:
      - plotterplots:/plots
    restart: always
    ports: 
      - 5010:5000

volumes:
  mongodbdata:
  plotterplots:
